version: '3.9'

services:
  app:
    build: .
    entrypoint:
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # port exposed : mysql port running inside container
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql